version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./src:/src
     - ./conf/nginx:/etc/nginx/conf.d
    links:
     - php
     - mysqldb
  php:
    build:
      context: ./conf
      dockerfile: Dockerfilephp
    image: php:7-fpm
    volumes:
      - ./src:/src
    environment:
      - MYSQL_PASSWORD=p@ssw0rd1
      - MYSQL_USER=root
      - MYSQL_HOST=mysqldb
      - MYSQL_DB=bookstore
  mysqldb:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
      - ./schema:/schema
      - ./schema/createdb.sh:/schema/createdb.sh
volumes:
  mysql:
  mysql_config: